pipeline {
    agent any
	
	tools {
	maven 'Maven 3.6.1'
	}
    
    stages{
        stage('build'){
            steps {
                echo 'building worker app'
                dir('worker'){
				sh 'mvn compile'
				}
            }
        
        }
        
         stage(two){
            steps {
                echo 'Testing worker app'
                sh 'mvn clean test'
            }
        
        }
        
         stage(three){
            steps {
                echo 'step3'
                sh 'mvn package'
            }
        
        }
        
    }
    
    post {
        always {
            echo 'this CI/CD pipeline is now completed'
			archiveArtifacts '**/target/*.jar'
        }
        
        
    }
    
}